# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'homeWorkLesson23(WheatherAndNews)2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for homeWorkLesson23(WheatherAndNews)2
  pod 'Alamofire', '~> 5.4'
  pod 'AlamofireNetworkActivityLogger', '~> 3.4'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SSBouncyButton', '~> 1.0'
  pod 'RealmSwift', '~>10'
  pod 'Firebase/RemoteConfig'
  
end
